import { type SecurityEvent } from "../services/api";
import { RefreshCw, Zap, ShieldCheck, EyeOff } from "lucide-react";

interface MutationActivityProps {
  events: SecurityEvent[];
}

export default function MutationActivity({ events }: MutationActivityProps) {
  const mutationEvents = events.filter((e) => e.event_type === "mutation");

  return (
    <div className="space-y-6 font-mono">
      {/* HEADER */}
      <div className="border-b border-slate-900 pb-4">
        <h2 className="text-xl font-bold text-slate-100 uppercase tracking-wider">MUTATION DECK</h2>
        <p className="text-xs text-slate-500">Chronological history of decoy assets generated by the Adaptive Mutation Engine.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* EXPLANATORY PANEL */}
        <div className="bg-slate-950 border border-slate-900 rounded-lg p-5 space-y-4">
          <h3 className="text-xs font-bold text-slate-200 uppercase tracking-wider flex items-center space-x-2 border-b border-slate-900 pb-3">
            <Zap className="h-4 w-4 text-amber-500" />
            <span>How Adaptive Deception Works</span>
          </h3>
          <p className="text-[11px] text-slate-400 leading-relaxed">
            Attackers scanning transaction chains or listing API endpoints look for stable high-value targets. To counter this, the **Adaptive Deception Engine** mutates the environment:
          </p>
          <ul className="list-disc list-inside space-y-2 text-[11px] text-slate-500">
            <li><strong className="text-slate-400">Honeytoken Accounts</strong>: Periodically creates fake corporate accounts with large mock balances.</li>
            <li><strong className="text-slate-400">Decoy APIs</strong>: Registers new restricted routing URLs to capture crawler requests.</li>
            <li><strong className="text-slate-400">Edge Fluctuations</strong>: Mutates regular node account balances by ±5% and creates mock transactions, shifting transaction patterns so attackers cannot rely on static intelligence.</li>
          </ul>
          <div className="pt-4 border-t border-slate-900 flex items-center space-x-2 text-[10px] text-cyber-accent">
            <ShieldCheck className="h-4 w-4" />
            <span className="font-semibold uppercase tracking-wider">Status: Deception Active</span>
          </div>
        </div>

        {/* LOGS LIST */}
        <div className="lg:col-span-2 bg-slate-950 border border-slate-900 rounded-lg overflow-hidden flex flex-col h-[550px]">
          <div className="bg-slate-900/60 px-5 py-3 border-b border-slate-900 flex items-center justify-between">
            <span className="text-xs font-bold text-slate-400 uppercase tracking-wider">Mutation Action History</span>
            <span className="text-[10px] text-slate-500">TOTAL LOGS: {mutationEvents.length}</span>
          </div>

          <div className="flex-1 overflow-y-auto divide-y divide-slate-900/60 p-4 space-y-4">
            {mutationEvents.length === 0 ? (
              <div className="h-full flex flex-col items-center justify-center text-slate-600 text-xs uppercase space-y-3">
                <EyeOff className="h-8 w-8 text-slate-700" />
                <span>No mutation events captured yet.</span>
              </div>
            ) : (
              mutationEvents.map((e, index) => {
                const details = e.details || {};
                return (
                  <div key={e.event_id} className="p-4 border border-slate-900 bg-slate-900/10 rounded-lg space-y-3 pulse-mutation">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center space-x-2">
                        <RefreshCw className="h-4 w-4 text-amber-500 animate-spin" style={{ animationDuration: "10s" }} />
                        <span className="text-xs font-bold text-slate-200">
                          MUTATION SEQUENCE #{details.mutation_cycle || mutationEvents.length - index}
                        </span>
                      </div>
                      <span className="text-[10px] text-slate-500">
                        {new Date(e.timestamp).toLocaleTimeString()}
                      </span>
                    </div>

                    <p className="text-xs text-slate-400">{e.description}</p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-[11px] font-mono">
                      <div className="p-2.5 bg-slate-950/65 rounded border border-slate-900 space-y-1">
                        <span className="text-[9px] text-slate-500 font-bold uppercase">Decoy Honeytoken Account</span>
                        <p className="text-slate-300 font-semibold truncate">
                          {details.new_honeytoken_account || "Generated"}
                        </p>
                      </div>
                      <div className="p-2.5 bg-slate-950/65 rounded border border-slate-900 space-y-1">
                        <span className="text-[9px] text-slate-500 font-bold uppercase">Decoy Honeytoken API</span>
                        <p className="text-slate-300 font-semibold truncate">
                          {details.new_honeytoken_api || "Generated"}
                        </p>
                      </div>
                    </div>

                    <div className="flex space-x-4 text-[10px] text-slate-500">
                      <span>Standard Accounts Adjusted: {details.mutated_accounts_count || 0}</span>
                      <span>Fake Transaction Trails: {details.new_transaction_trails || 0}</span>
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
